### ISSUE TITLE
Clear instructions for non-developers to install and use the app. 

### ISSUE THREAD

**Issue by Jaheay** [AhmedSherifH/Book-Scraper#7]
**Is your feature request related to a problem? Please describe.**
The project lacks requirement for python module installation, which can be easily fixed with pipreqs. 
This project also lacks documentation on installation and usage. 

A pull request was previous submitted to encourage the author to implement these, but they were promptly removed in the next commit. 

**Describe the solution you'd like**
Good, clear, plain language documentation on the installation of dependencies and the usage of the application.

**Comment by AhmedSherifH** [comment]
Thank you for the pull request, I have just merged it. I'm sorry about merging then reverting your previous PR, I think it included some errors on how to run the program; I should've been more clear on how the program operates. Thanks again for the PR!
